In [1]:
import pandas as pd

In [2]:
cust = pd.read_csv("custdata.tsv", sep="\t")

print(cust.shape)
display(cust[["age", "income", "num.vehicles"]].describe())

(1000, 11)

               age         income  num.vehicles
count  1000.000000    1000.000000    944.000000
mean     51.699815   53504.771000      1.916314
std      18.863433   65478.065729      1.101618
min       0.000000   -8700.000000      0.000000
25%      38.000000   14600.000000      1.000000
50%      50.000000   35000.000000      2.000000
75%      64.000000   67000.000000      2.000000
max     146.680197  615000.000000      6.000000

In [4]:
cust[["age", "income", "num.vehicles"]].corr()

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000

Correlation before cleaning data

In [7]:
print("Age 0 or less:",(cust["age"]<= 0).sum())

Age 0 or less: 3

In [8]:
print("Age over 100:",(cust["age"] > 100).sum())

Age over 100: 8

In [9]:
print("Negative income:",(cust["income"] < 0).sum())

Negative income: 1

In [10]:
print("Missing vehicle values:",cust["num.vehicles"].isna().sum())

Missing vehicle values: 56

In [12]:
cust_clean = cust[cust["age"] > 0]
cust_clean = cust_clean[cust_clean["age"] <= 100]
cust_clean = cust_clean[cust_clean["income"] >= 0]
cust_clean = cust_clean.dropna(subset=["num.vehicles"])

In [13]:
print(cust_clean.shape)
print("Total rows removed:", len(cust) - len(cust_clean))

(932, 11)
Total rows removed: 68

Correlations after cleaning data

In [14]:
cust_clean[["age", "income", "num.vehicles"]].corr()

                   age    income  num.vehicles
age           1.000000 -0.002644     -0.066295
income       -0.002644  1.000000      0.137859
num.vehicles -0.066295  0.137859      1.000000

Cleaning data: removed 3 ages that were 0 or less, removed 8 ages that were over 100, removed negative income, removed 56 rows that had missing vehicle data. A total of 68 rows were removed.There were all removed because they seemed like errors (invalid) or simply missing data and removed to not affect any correlations.

Anaylsis: There is weak correlation for all values.

AI USE: Chat gpt
- Syntax for cleaning data, did not realize had to enter at once. W